package org.janelia.model.sage;

// Generated Jan 14, 2014 11:00:59 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * CvTermRelationship generated by hbm2java
 */
public class CvTermRelationship implements Serializable {

    private Integer id;
    private CvTerm type;
    private CvTerm object;
    private CvTerm subject;
    private boolean isCurrent;
    private Date createDate;

    public CvTermRelationship() {
    }

    public CvTermRelationship(CvTerm type, CvTerm object, CvTerm subject, boolean isCurrent, Date createDate) {
        this.type = type;
        this.object = object;
        this.subject = subject;
        this.isCurrent = isCurrent;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CvTerm getType() {
        return this.type;
    }

    public void setType(CvTerm type) {
        this.type = type;
    }

    public CvTerm getObject() {
        return this.object;
    }

    public void setObject(CvTerm object) {
        this.object = object;
    }

    public CvTerm getSubject() {
        return this.subject;
    }

    public void setSubject(CvTerm subject) {
        this.subject = subject;
    }

    public boolean getIsCurrent() {
        return this.isCurrent;
    }

    public void setIsCurrent(boolean isCurrent) {
        this.isCurrent = isCurrent;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
