package org.janelia.model.sage;

// Generated Jan 14, 2014 11:00:59 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * ImageProperty generated by hbm2java
 */
public class ImageProperty implements Serializable {

    private Integer id;
    private CvTerm type;
    private Image image;
    private String value;
    private Date createDate;

    public ImageProperty() {
    }

    public ImageProperty(CvTerm type, Image image, String value, Date createDate) {
        this.type = type;
        this.image = image;
        this.value = value;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CvTerm getType() {
        return this.type;
    }

    public void setType(CvTerm cvTerm) {
        this.type = cvTerm;
    }

    public Image getImage() {
        return this.image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    
}
