package org.janelia.it.jacs.model.sage;

// Generated Jan 14, 2014 11:00:59 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cv generated by hbm2java
 */
public class Cv implements Serializable {

    private Integer id;
    private byte version;
    private String name;
    private String definition;
    private boolean isCurrent;
    private String displayName;
    private Date createDate;
    private Set<CvTerm> terms = new HashSet<CvTerm>(0);

    public Cv() {
    }

    public Cv(String name, boolean isCurrent, Date createDate) {
        this.name = name;
        this.isCurrent = isCurrent;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public byte getVersion() {
        return this.version;
    }

    public void setVersion(byte version) {
        this.version = version;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDefinition() {
        return this.definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public boolean getIsCurrent() {
        return this.isCurrent;
    }

    public void setIsCurrent(boolean isCurrent) {
        this.isCurrent = isCurrent;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Set<CvTerm> getTerms() {
        return this.terms;
    }

    public void setTerms(Set<CvTerm> terms) {
        this.terms = terms;
    }
}
