package org.janelia.it.jacs.model.sage;

// Generated Jan 14, 2014 11:00:59 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * CvTerm generated by hbm2java
 */
public class CvTerm implements Serializable {

    private Integer id;
    private Cv cv;
    private String name;
    private String definition;
    private byte isCurrent;
    private String displayName;
    private String dataType;
    private Date createDate;

    public CvTerm() {
    }

    public CvTerm(Cv cv, String name, byte isCurrent, Date createDate) {
        this.cv = cv;
        this.name = name;
        this.isCurrent = isCurrent;
        this.createDate = createDate;
    }

    public CvTerm(Cv cv, String name, String definition, byte isCurrent, String displayName, String dataType,
            Date createDate) {
        this.cv = cv;
        this.name = name;
        this.definition = definition;
        this.isCurrent = isCurrent;
        this.displayName = displayName;
        this.dataType = dataType;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Cv getCv() {
        return this.cv;
    }

    public void setCv(Cv cv) {
        this.cv = cv;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDefinition() {
        return this.definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public byte getIsCurrent() {
        return this.isCurrent;
    }

    public void setIsCurrent(byte isCurrent) {
        this.isCurrent = isCurrent;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDataType() {
        return this.dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        CvTerm other = (CvTerm) obj;
        if (getId() == null) {
            if (other.getId() != null) return false;
        }
        else if (!getId().equals(other.getId())) return false;
        return true;
    }
}
