package org.janelia.it.jacs.model.sage;

// Generated Nov 2, 2015 2:36:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExperimentRelationship generated by hbm2java
 */
public class ExperimentRelationship implements java.io.Serializable {

    private Integer id;
    private CvTerm type;
    private Experiment object;
    private Experiment subject;
    private Date createDate;

    public ExperimentRelationship() {
    }

    public ExperimentRelationship(CvTerm type, Experiment object, Experiment subject, Date createDate) {
        this.type = type;
        this.object = object;
        this.subject = subject;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CvTerm getType() {
        return this.type;
    }

    public void setType(CvTerm type) {
        this.type = type;
    }

    public Experiment getObject() {
        return this.object;
    }

    public void setObject(Experiment object) {
        this.object = object;
    }

    public Experiment getSubject() {
        return this.subject;
    }

    public void setSubject(Experiment subject) {
        this.subject = subject;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
