package org.janelia.it.jacs.model.sage;

// Generated Nov 2, 2015 2:36:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExperimentProperty generated by hbm2java
 */
public class ExperimentProperty implements java.io.Serializable {

    private Integer id;
    private CvTerm type;
    private Experiment experiment;
    private String value;
    private Date createDate;

    public ExperimentProperty() {
    }

    public ExperimentProperty(CvTerm cvTerm, Experiment experiment, String value, Date createDate) {
        this.type = cvTerm;
        this.experiment = experiment;
        this.value = value;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CvTerm getType() {
        return this.type;
    }

    public void setType(CvTerm type) {
        this.type = type;
    }

    public Experiment getExperiment() {
        return this.experiment;
    }

    public void setExperiment(Experiment experiment) {
        this.experiment = experiment;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
