package org.janelia.it.jacs.model.sage;

// Generated Jan 14, 2014 11:00:59 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Line generated by hbm2java
 */
public class Line implements Serializable {

    private Integer id;
    private CvTerm lab;
    private String name;
    private Integer geneId;
    private Integer organismId;
    private String genotype;
    private Date createDate;
    private Set<Image> images = new HashSet<Image>(0);

    public Line() {
    }

    public Line(CvTerm lab, String name, Date createDate) {
        this.lab = lab;
        this.name = name;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CvTerm getLab() {
        return this.lab;
    }

    public void setLab(CvTerm lab) {
        this.lab = lab;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getGeneId() {
        return this.geneId;
    }

    public void setGeneId(Integer geneId) {
        this.geneId = geneId;
    }

    public Integer getOrganismId() {
        return this.organismId;
    }

    public void setOrganismId(Integer organismId) {
        this.organismId = organismId;
    }

    public String getGenotype() {
        return this.genotype;
    }

    public void setGenotype(String genotype) {
        this.genotype = genotype;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Set<Image> getImages() {
        return this.images;
    }

    public void setImages(Set<Image> images) {
        this.images = images;
    }

}
