package org.janelia.it.jacs.model.sage;

// Generated Oct 9, 2015 2:22:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Session generated by hbm2java
 */
public class SageSession implements java.io.Serializable {

    private Integer id;
    private CvTerm type;
    private CvTerm lab;
    private Image image;
    private Line line;
    private String name;
    private Experiment experiment;
    private Integer phaseId;
    private String annotator;
    private Date createDate;
    private Set<Observation> observations = new HashSet<>(0);

    public SageSession() {
    }

    public SageSession(CvTerm type, CvTerm lab, Line line, String name, Experiment experiment, String annotator, Date createDate) {
        this.type = type;
        this.lab = lab;
        this.line = line;
        this.name = name;
        this.experiment = experiment;
        this.annotator = annotator;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CvTerm getType() {
        return this.type;
    }

    public void setType(CvTerm type) {
        this.type = type;
    }

    public CvTerm getLab() {
        return this.lab;
    }

    public void setLab(CvTerm lab) {
        this.lab = lab;
    }

    public Image getImage() {
        return this.image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    public Line getLine() {
        return this.line;
    }

    public void setLine(Line line) {
        this.line = line;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Experiment getExperiment() {
        return this.experiment;
    }

    public void setExperiment(Experiment experiment) {
        this.experiment = experiment;
    }

    public Integer getPhaseId() {
        return this.phaseId;
    }

    public void setPhaseId(Integer phaseId) {
        this.phaseId = phaseId;
    }

    public String getAnnotator() {
        return this.annotator;
    }

    public void setAnnotator(String annotator) {
        this.annotator = annotator;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Set<Observation> getObservations() {
        return this.observations;
    }

    public void setObservations(Set<Observation> observations) {
        this.observations = observations;
    }

}
