package org.janelia.model.security;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;

/**
 * A user in the Workstation system who can be part of one or more groups.
 *
 * Users can optionally be authenticated by JACS, in which case the password field should contain a salted
 * password hash generated by JACS. If external authentication mechanism is used, then the password is empty.
 *
 * @author <a href="mailto:rokickik@janelia.hhmi.org">Konrad Rokicki</a>
 */
public class User extends Subject {

    private String password;
    private String email;
    private Set<UserGroupRole> userGroupRoles = new HashSet<>();

    /**
     * Hashed password. This is not a required field. If this is undefined, it's expected that the user will be
     * authenticated against an external service such as LDAP or AD.
     */
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set<UserGroupRole> getUserGroupRoles() {
        return userGroupRoles;
    }

    public void setUserGroupRoles(Set<UserGroupRole> userGroupRoles) {
        if (userGroupRoles==null) throw new IllegalArgumentException("Property cannot be null");
        this.userGroupRoles = userGroupRoles;
    }
    
    public void setUserGroupRole(String groupKey, GroupRole role) {
        UserGroupRole ugr = getRole(groupKey);
        if (ugr==null) {
            userGroupRoles.add(new UserGroupRole(groupKey, role));
        }
        else {
            ugr.setRole(role);
        }
    }
    
    public GroupRole getUserGroupRole(String groupKey) {
        UserGroupRole ugr = getRole(groupKey);
        return ugr==null ? null : ugr.getRole();
    }

    @JsonIgnore
    public Set<String> getReadGroups() {
        Set<String> groups = new HashSet<>();
        for(UserGroupRole groupRole : userGroupRoles) {
            if (groupRole.getRole().isRead()) {
                groups.add(groupRole.getGroupKey());
            }
        }
        return groups;
    }

    @JsonIgnore
    public Set<String> getWriteGroups() {
        Set<String> groups = new HashSet<>();
        for(UserGroupRole groupRole : userGroupRoles) {
            if (groupRole.getRole().isWrite()) {
                groups.add(groupRole.getGroupKey());
            }
        }
        return groups;
    }
    
    public boolean hasGroupRead(String groupKey) {
        return userGroupRoles.stream()
                .filter(groupRole -> groupRole.getGroupKey().equals(groupKey))
                .filter(groupRole -> groupRole.getRole().isRead())
                .findFirst()
                .map(userGroupRole -> true)
                .orElse(false)
                ;
    }

    public boolean hasGroupWrite(String groupKey) {
        return userGroupRoles.stream()
                .filter(groupRole -> groupRole.getGroupKey().equals(groupKey))
                .filter(groupRole -> groupRole.getRole().isWrite())
                .findFirst()
                .map(userGroupRole -> true)
                .orElse(false)
                ;
    }
    
    public UserGroupRole getRole(String groupKey) {
        for(UserGroupRole groupRole : userGroupRoles) {
            if (groupRole.getGroupKey().equals(groupKey)) {
                return groupRole;
            }
        }
        return null;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("User[");
        if (getId() != null) {
            builder.append("id=");
            builder.append(getId());
            builder.append(", ");
        }
        if (getKey() != null) {
            builder.append("key=");
            builder.append(getKey());
            builder.append(", ");
        }
        if (getName() != null) {
            builder.append("name=");
            builder.append(getName());
            builder.append(", ");
        }
        if (getFullName() != null) {
            builder.append("fullName=");
            builder.append(getFullName());
            builder.append(", ");
        }
        if (email != null) {
            builder.append("email=");
            builder.append(email);
            builder.append(", ");
        }
        if (password != null) {
            builder.append("hasPassword");
        }
        builder.append("]");
        return builder.toString();
    }
}
